### ISSUE TITLE
[Feature]: Cue skills development

### ISSUE THREAD

**Issue by adrienfort** [PoCInnovation/DagViz#4]
### Description

Learn Cue language :rocket:

### Expected behaviour

Here is what you have to do :

> [cuelang.org](https://cuelang.org) will be your best friend

> [Cuelang GitHub](https://github.com/cue-lang)

- [x] Read [Cue introduction](https://cuelang.org/docs/about/)
- [x] Read [Cue use cases](https://cuelang.org/docs/usecases/)
- [x] Read the [logic of Cue](https://cuelang.org/docs/concepts/logic/)
- [x] Read [Cue specifications](https://cuelang.org/docs/references/spec/)
- [x] Follow all the [Cue tutorials](https://cuelang.org/docs/tutorials/)
- [x] Write a Cue program that validates GitHub Actions
- [x] Call @TomChv to review your Cue program

### Environment

/

### Proposed solution

/

**Comment by TomChv** [comment]
You can also check [Cuetorials](https://cuetorials.com/introduction/), it's a good complement to officiel cue website.

Specially about [Cue API](https://cuetorials.com/go-api/), you'll need to master that one to complete your project ;)

**Comment by adrienfort** [comment]
> You can also check [Cuetorials](https://cuetorials.com/introduction/), it's a good complement to officiel cue website.
> 
> Specially about [Cue API](https://cuetorials.com/go-api/), you'll need to master that one to complete your project ;)

Thanks ! I was trying to find this website :+1:
